# Generated by Django 3.1.1 on 2020-09-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=8)),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Total_Leave', models.IntegerField(default=0)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('LID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Description', models.TextField()),
                ('Leave_Status', models.BooleanField(default=False)),
                ('Seen_By_Manager', models.BooleanField(default=False)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.user')),
            ],
            options={
                'db_table': 'Leave',
            },
        ),
    ]
